[tool.ruff]
select = ["*"]

# Ignore F401 to avoid warnings or fixes related to unused imports
ignore = ["F401"]

# Exclude specific directories
exclude = ["__pycache__", ".git", "venv", "env"]

# Enable automatic fixing, but unused imports will be ignored
fix = true

# Specify line-length
line-length = 88
