[tool.ruff]
#select = ["*"]
fixable = ["*", "!F401"]  
# Exclude specific directories
exclude = ["__pycache__", ".git", "venv", "env"]
# Exclude specific directories and files from checks (if needed)
exclude = ["__pycache__", ".git", "venv", "env"]

# Set maximum line length (default is 88)
line-length = 88

# Enable type checking (if using type annotations)
enable-type-checking = true